### ISSUE TITLE
Packaging scipy

### ISSUE THREAD

**Issue by Siecje** [takluyver/pynsist#106]
I'm trying to create an installer for code that uses scipy.

```
C:\Users\IEUser\Desktop>pqml Hello.qml
Traceback (most recent call last):
  File "C:\Program Files\QML Application\bin\pqml-script.py", line 15, in <module>
    main()
#...
    import seaborn as sns # TODO: load default colormap from somewhere else..
  File "C:\Program Files\QML Application\pkgs\seaborn\__init__.py", line 6, in <
module>
    from .rcmod import *
  File "C:\Program Files\QML Application\pkgs\seaborn\rcmod.py", line 8, in <mod
ule>
    from . import palettes, _orig_rc_params
  File "C:\Program Files\QML Application\pkgs\seaborn\palettes.py", line 12, in
<module>
    from .utils import desaturate, set_hls_values, get_color_cycle
  File "C:\Program Files\QML Application\pkgs\seaborn\utils.py", line 8, in <mod
ule>
    from scipy import stats
  File "C:\Program Files\QML Application\pkgs\scipy\stats\__init__.py", line 344
, in <module>
    from .stats import *
  File "C:\Program Files\QML Application\pkgs\scipy\stats\stats.py", line 173, i
n <module>
    import scipy.special as special
  File "C:\Program Files\QML Application\pkgs\scipy\special\__init__.py", line 6
36, in <module>
    from ._ufuncs import *
ImportError: DLL load failed: The specified module could not be found.
```

Since there is no 32-bit Windows wheel for scipy it is in the packages section of the `pynsist` config.

`packages = scipy`

The import comes from 32-bit Anaconda. When I run dependency walker on 

```C:\Program Files\QML Application\pkgs\scipy\special\_ufuncs.cp35-win32.pyd```

It lists some .dll files that are present in Anaconda.

```
libifcoremd.dll
libmmd.dll
mkl_intel_thread.dll
```

I copied the those in the `Python` directory (I am using pynsist from master). But the import still complains about a missing .dll. When I run dependency walker on `libmmd.dll` there is a circular dependency. 

`api-ms-win-core-processthreads-l1-1-0.dll depending on kernel32.dll which depends on api-ms-win-core-processthreads-l1-1-0.dll`

`kernel32.dll` comes from `c:\windows\system32\kernel32.dll` and this is for a 32-bit Window installation.

I also saw this circular dependency when trying to create a cx_Freeze installer for this application.

Pynsist works great when there is a wheel on pypi for the platform.

**Comment by takluyver** [comment]
`scipy` is unfortunately a tricky thing to package. Maybe try getting files from the wheels available on [Gohlke's page](http://www.lfd.uci.edu/~gohlke/pythonlibs/#scipy)? If you do that, you may have to get numpy from there too, though I'm not sure.

**Comment by Siecje** [comment]
How do I tell pynsist to use a local wheel?

Also do you know why scipy doesn't have Windows wheels?

**Comment by takluyver** [comment]
There isn't currently a way to tell it to use a local wheel, though that may get added at some point. You'll have to unpack it manually into pynsist_pkgs.

I don't know why scipy doesn't have Windows wheels, but I believe it's tricky to build, and there are licensing issues about distributing it depending on what libraries you build against.

**Comment by Siecje** [comment]
Thanks! Extracting the wheels into `pynsist_pkgs` worked great.

The [numpy+mkl](http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy) wheel from there was also required.

**Comment by takluyver** [comment]
Thanks! I've opened #107 to think more about including wheels not from PyPI.
