### ISSUE TITLE
pynsist downloads the embedded Python zip to a folder named "~"

### ISSUE THREAD

**Issue by brechtm** [takluyver/pynsist#109]
On Windows, pynsist creates a folder named `~` in the CWD. It contains `AppData/Local/pynsist`. I suppose you want to write to the user's home/profile directory instead?

**Comment by takluyver** [comment]
Yep, it should use the home directory. The code looks right, though:
https://github.com/takluyver/pynsist/blob/e01d6f08eb71bc5aa2d294f5369a736e59becd09/nsist/util.py#L45

Is your `%LOCALAPPDATA%` environment variable set?

**Comment by brechtm** [comment]
Ah. I'm running pynsist from a tox env, so I need to add `LOCALAPPDATA` to passenv.

**Comment by takluyver** [comment]
There should be a fallback if it can't find LOCALAPPDATA, but the fallback needs one of:

* HOME
* USERPROFILE
* HOMEPATH

If none of those are set, then you get `~` as a directory.

**Comment by takluyver** [comment]
Closing as it sounds like this was due to missing environment variables, and I don't know how I could add a fallback for when all the existing fallbacks fail. ;-)

**Comment by brechtm** [comment]
It's working for me now (by passing `LOCALAPPDATA` in tox), but you could perhaps output a warning when running on Windows and `LOCALAPPDATA` is not set?

**Comment by takluyver** [comment]
OK, that makes sense.
