### ISSUE TITLE
sendto for installed app

### ISSUE THREAD

**Issue by johannes-otto** [takluyver/pynsist#110]
Hi,
I got some small file conversion tools, they are used via sendto. Is there a way to make a shortcut in shell:sendto or an entry in the context-menu via the install script?

**Comment by takluyver** [comment]
There's no support for that built into Pynsist, but if you can figure out the NSIS commands to do it, you can specify a custom template for the NSI file and add them to the installation process.

**Comment by johannes-otto** [comment]
thanks
