### ISSUE TITLE
Allow config values to start on a new line

### ISSUE THREAD

**Issue by Siecje** [takluyver/pynsist#112]
The config file should allow the first value to be on a new line.

It is a gotcha that I ran into when first using `pynsist` https://github.com/takluyver/pynsist/issues/72#issuecomment-247709276

Here is an example of a config file that doesn't require the value to be on the same line.
https://bitbucket.org/ned/coveragepy/src/070cc5e61045982871ca01e194ae3fa4e2de614a/setup.cfg?at=default&fileviewer=file-view-default

**Comment by takluyver** [comment]
Makes sense - do you want to do a PR?
