### ISSUE TITLE
Can't extract wheels in 2.7

### ISSUE THREAD

**Issue by gricey432** [takluyver/pynsist#116]
Commit 7c70637 uses `exist_ok` which isn't backward compatible to 2.7

**Comment by Siecje** [comment]
I guess the backport of `pathlib` doesn't have that parameter?

https://docs.python.org/3/library/pathlib.html#pathlib.Path.mkdir

https://pypi.python.org/pypi/pathlib/

**Comment by takluyver** [comment]
We should probably switch to pathlib2 for the backport; hopefully that does have the parameter.

**Comment by gricey432** [comment]
It looks like pathlib2 does have it
https://github.com/mcmtroffaes/pathlib2/blob/develop/pathlib2.py#L1430

**Comment by takluyver** [comment]
Great :-) Anyone want to do a PR?

**Comment by gricey432** [comment]
I was writing one but I couldn't see how to run it locally cause there's no `setup.py` so I figured I'd have another look later

**Comment by takluyver** [comment]
That commit should do it. The packaging uses [flit](http://flit.readthedocs.io/en/latest/), which does make it a bit awkward on Python 2, but I'm planning to make Pynsist require Python 3 soon anyway (#99).

**Comment by takluyver** [comment]
I've stuck a new release (1.12) up with this fixed.
