### ISSUE TITLE
Including PyPi wheels fails on Python < 3.5

### ISSUE THREAD

**Issue by jswetzen** [takluyver/pynsist#118]
[pypi.py](https://github.com/takluyver/pynsist/blob/master/nsist/pypi.py#L189) gets an error because the `exists_ok` parameter was only added in Python 3.5.

I'm building a GUI application with PySide, including it with `pypi_wheels=PySide==1.2.4` in the config. Python 3.4 is the newest version supported by PySide, so I'd prefer to use that for everything. Besides, the README says Python 3.3 is supported by pynsist, so maybe the `exists_ok` feature shouldn't be used?

**Comment by takluyver** [comment]
Ah, that's annoying. Yes, we should probably avoid using exists_ok, then.

**Comment by jswetzen** [comment]
That was quick, thanks!
