### ISSUE TITLE
Issues with scrapy (cryptography) in application

### ISSUE THREAD

**Issue by mclean25** [takluyver/pynsist#120]
With every install of my .exe  on any other computer than my own, I get the following error raised when running the program:

```
 ... a bunch of stuff:
File "C:\Program Files\secPull\pkgs\cryptography\hazmat\bindings\openssl\binding.py", line 12, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: DLL load failed: The specified module could not be found.
```

After many uninstalls/re installs of all the packages, I can't for the life of me understand where this problem is coming from. The program works perfectly fine when (a) running the script via command line on my own computer and (b) running the exe program compiled by pynsist on my own computer. But I always run into the same error on other computers. This leads me to believe that `pyinsyst` is somehow not loading the right libraries?

As I'm running windows, I use conda for all my packages, as recommended by `scrapy`. I've uninstalled and reinstalled all of them just to be sure there wasn't a corrupt version that was causing the issue.  

**conda list:**

```
C:\Users\alexm_iem8de4\Desktop\secPull>conda list
 packages in environment at C:\Users\alexm_iem8de4\Miniconda3:

asn1crypto                0.22.0                   py36_0
attrs                     17.2.0                   py36_0    conda-forge
automat                   0.5.0                    py36_0
Automat                   0.6.0                     <pip>
cffi                      1.10.0                   py36_0
conda                     4.3.22                   py36_0
conda-env                 2.6.0                         0
console_shortcut          0.1.1                    py36_1
constantly                15.1.0                   py36_0
cryptography              1.9                       <pip>
cryptography              1.8.1                    py36_0
cssselect                 1.0.1                    py36_0
hyperlink                 17.1.1                   py36_0
hyperlink                 17.2.1                    <pip>
hypothesis                3.11.0                   py36_0    conda-forge
idna                      2.5                      py36_0
incremental               17.5.0                    <pip>
incremental               16.10.1                  py36_0
Jinja2                    2.9.6                     <pip>
libiconv                  1.14                     vc14_4  [vc14]  conda-forge
libxml2                   2.9.4                    vc14_4  [vc14]  conda-forge
libxslt                   1.1.29                   vc14_4  [vc14]  conda-forge
lxml                      3.8.0                    py36_0
MarkupSafe                1.0                       <pip>
menuinst                  1.4.7                    py36_0
openssl                   1.0.2l                   vc14_0  [vc14]
packaging                 16.8                     py36_0
parsel                    1.2.0                    py36_0
pip                       9.0.1                    py36_1
pyasn1                    0.2.3                    py36_0    conda-forge
pyasn1-modules            0.0.9                     <pip>
pyasn1-modules            0.0.8                    py36_0    conda-forge
pycosat                   0.6.2                    py36_0
pycparser                 2.17                     py36_0
pydispatcher              2.0.5                    py36_0    conda-forge
pympler                   0.5                      py36_0    conda-forge
pynsist                   1.12                      <pip>
pyopenssl                 17.0.0                   py36_0
pyparsing                 2.1.4                    py36_0
python                    3.6.1                         2
pywin32                   220                      py36_2
queuelib                  1.4.2                    py36_0
requests                  2.14.2                   py36_0
requests_download         0.1.1                     <pip>
ruamel_yaml               0.11.14                  py36_1
scrapy                    1.3.3                    py36_0
service-identity          17.0.0                    <pip>
service_identity          16.0.0                   py36_0
setuptools                36.0.1                    <pip>
setuptools                27.2.0                   py36_1
six                       1.10.0                   py36_0
twisted                   17.5.0                   py36_0
vc                        14                            0    conda-forge
vs2015_runtime            14.0.25123                    0
w3lib                     1.17.0                   py36_0
wheel                     0.29.0                   py36_0
win_cli_launchers         0.1                       <pip>
yarg                      0.1.9                     <pip>
zlib                      1.2.11                   vc14_0  [vc14]  conda-forge
zope                      1.0                      py36_0
zope.interface            4.4.2                    py36_0
```

**pip freeze:**
```
asn1crypto==0.22.0
attrs==17.2.0
Automat==0.6.0
cffi==1.10.0
conda==4.3.22
constantly==15.1.0
cryptography==1.9
cssselect==1.0.1
hyperlink==17.2.1
hypothesis==3.11.0
idna==2.5
incremental==17.5.0
Jinja2==2.9.6
lxml==3.8.0
MarkupSafe==1.0
menuinst==1.4.7
packaging==16.8
parsel==1.2.0
pyasn1==0.2.3
pyasn1-modules==0.0.9
pycosat==0.6.2
pycparser==2.17
PyDispatcher==2.0.5
Pympler==0.5
pynsist==1.12
pyOpenSSL==17.0.0
pyparsing==2.1.4
pywin32==220
queuelib==1.4.2
requests==2.14.2
requests-download==0.1.1
Scrapy==1.3.3
service-identity==17.0.0
six==1.10.0
Twisted==17.5.0
w3lib==1.17.0
win-cli-launchers==0.1
yarg==0.1.9
zope.interface==4.4.2
```

**installer.cfg:**
```
[Application]
name=secPull
version=0.1.8
entry_point=start:main
console=true
icon=icon.ico

[Python]
version=3.6.0
bitness=64
format=bundled

[Include]
Importable packages that your application requires, one per line
packages = scrapy
     subprocess
     os
     csv
     re
     time
     sys
     datetime
     six
     wheel
     cffi
     incremental
     cryptography
     automat
     asn1crypto
     jinja2
     constantly
     w3lib
     conda
     parsel
     pyasn1
     pycparser
     hyperlink
     cssselect
     setuptools
     pycosat
     yarg
     menuinst
     lxml
     markupsafe
     pyparsing
     idna
     requests
     packaging
     twisted
     pip
     queuelib
     zope
     pydispatch
     secCrawl
     OpenSSL
     _cffi_backend
     service_identity
     pyasn1_modules
     attr
     win32api
     win32pipe
     win32file
     pywintypes
     _win32sysloader
     win_cli_launchers

[Command start]
entry_point=start:main
```

I only installed python via conda on my computer. Is there an issue with pynsist not recognizing the right packages from conda vs. pip?

**Comment by takluyver** [comment]
That error ("DLL load failed: The specified module could not be found.") usually means that the Python DLL you're using is linked against another one which is missing. You may be able to use [Dependency walker](http://www.dependencywalker.com/) to work out which it is.

As [cryptography](https://pypi.python.org/pypi/cryptography) has Windows wheels available, it may be better to use those by specifying the package under `pypi_wheels = cryptography==1.9`, rather than in the `packages` section. That will download cryptography from PyPI rather than copying it from the conda installation on your computer. Pynsist doesn't do anything clever with finding required DLLs, but wheel packages usually contain all the non-system DLLs they need.

**Comment by mclean25** [comment]
Thanks for your quick response. Where do I put `pypi_wheels = cryptography==1.9`?

**Comment by takluyver** [comment]
In `installer.cfg`, under the `[Include]` section. See the example here for reference:

https://github.com/takluyver/pynsist/blob/master/examples/pyqt5_opencv/installer.cfg

**Comment by mclean25** [comment]
So that worked, but I'm now getting the following error: 
```
File "CL\Program Files\secPull\pkgs\twisted\internet\_win32stdio.py", line 9 in <module>
   import win32api
ImportError: DLL load failed: the specified module could not be found.
```

I've tried adding `pypi_wheels = pywin32==220` and `pypi_wheels = twisted==17.5` but both yielded a `TypeError: NoneType not iterable` which I'm guessing means they're not available via `pypi_wheels`. Do you have any recommendations?

**Comment by takluyver** [comment]
Pywin32 is a bear to work with, unfortunately. It's used in the [pywebview example](https://github.com/takluyver/pynsist/tree/1.12/examples/pywebview), but I haven't been able to figure out a solution that doesn't require the user separately installing another MSVC runtime. `pypiwin32` looks promising, but apparently not quite promising enough.

So the only things I can suggest - and I realise these aren't good suggestions - are:

1. Use dependency walker to figure out which DLLs it's missing.
2. Try patching twisted to use [pywin32-ctypes](https://pypi.python.org/pypi/pywin32-ctypes) if that has the necessary functions.
3. Avoid using twisted or anything else which depends on pywin32.

**Comment by mclean25** [comment]
Okay, so I mimicked what you did for `pywebview` and now I get errors installing the program such as:
"""
Error opening file for writing:
C:\Program Files\secPull\Python\_bz2.pyd
"""
and 
"""
Error opening file for writing:
C:\Program Files\secPull\Python\_ctypes.pyd
"""

Other python files it has errors opening for writing are:

1. `_decimal.pyd`
2. `_hashlib.pyd`
3. `_lzma.pyd`
4. `_socket.pyd`
5. `_sqlite3.pyd`
6. `_ssl.pyd`

etc...

**Comment by takluyver** [comment]
Those errors sounds like something had those files open when you were trying to overwrite them - e.g. if you have the application running when you run the installer, that could happen.

I don't know about the redistributable package, unfortunately. Maybe pywin32 needs one specific version, or maybe it's some other DLL that it's missing.

**Comment by mclean25** [comment]
Yes; my bad.

How do I run the `./download.sh` on windows?

**Comment by mclean25** [comment]
Yes, my apologies on the last one. After realizing I forgot to run ./download.sh to copy `pywin32` modules over, I'm running into the following issue when running `pynsist installer.cfg`:

```
alex@Alex-PC:/mnt/c/Users/alexa/Desktop/secPull$ pynsist installer.cfg
Unpacking Python...
Copying packages into build directory...
Using cached wheel: setuptools-27.2.0-py2.py3-none-any.whl
Using cached wheel: incremental-16.10.1-py2.py3-none-any.whl
Using cached wheel: hyperlink-17.1.1-py2.py3-none-any.whl
Using cached wheel: Automat-0.5.0-py2.py3-none-any.whl
Using cached wheel: pyasn1_modules-0.0.8-py2.py3-none-any.whl
Using cached wheel: service_identity-16.0.0-py2.py3-none-any.whl
Traceback (most recent call last):
  File "/home/alex/anaconda3/bin/pynsist", line 11, in <module>
    sys.exit(main())
  File "/home/alex/anaconda3/lib/python3.5/site-packages/nsist/__init__.py", line 540, in main
    InstallerBuilder(**args).run(makensis=(not options.no_makensis))
  File "/home/alex/anaconda3/lib/python3.5/site-packages/nsist/__init__.py", line 495, in run
    self.prepare_packages()
  File "/home/alex/anaconda3/lib/python3.5/site-packages/nsist/__init__.py", line 381, in prepare_packages
    py_version=self.py_version, exclude=self.exclude)
  File "/home/alex/anaconda3/lib/python3.5/site-packages/nsist/copymodules.py", line 224, in copy_modules
    mc.copy(modname, target, exclude)
  File "/home/alex/anaconda3/lib/python3.5/site-packages/nsist/copymodules.py", line 119, in copy
    check_ext_mod(loader.path, self.py_version)
  File "/home/alex/anaconda3/lib/python3.5/site-packages/nsist/copymodules.py", line 30, in check_ext_mod
    raise ExtensionModuleMismatch(extensionmod_errmsg % ('Windows', path))
nsist.copymodules.ExtensionModuleMismatch: Found an extension module that will not be usable on Windows:
/home/alex/anaconda3/lib/python3.5/site-packages/pycosat.so
Put Windows packages in pynsist_pkgs/ to avoid this.
```

**Comment by takluyver** [comment]
The download.sh script is there because I'm a bit lazy - it could be a portable Python script, but those operations - downloading, unpacking and moving files around, are more convenient in shell scripting, and I usually use Linux.

If you need any packages with compiled parts, (like `pycosat`), you can't build the installed on Linux and copy them from your system, because the compiled libraries will be Linux `.so` files instead of Windows `.pyd` files. You need to do **one of** these things:

1. Get those packages from wheels using `pypi_wheels` in the config file. Pynsist will find and use Windows wheels regardless of the platform you're building on.
2. Find the Windows versions of the libraries manually and put them in `pynsist_pkgs` before calling `pynsist`.
3. Run `pynsist` on Windows, so that it can copy Windows versions of the libraries.

**Comment by mclean25** [comment]
I failed to post here shortly after my last response, I used bash on Ubuntu on Windows to run the `download.sh` file. Everything is finally working now, thanks for your help. Hopefully this dialogue can help others down the road.

**Comment by takluyver** [comment]
Great, thanks for the follow up :-)
