### ISSUE TITLE
Getting embeded Python zip from Disk

### ISSUE THREAD

**Issue by BerciMihai** [takluyver/pynsist#122]
When building an installer, it tries to get the Python 3.6.0 Embedded from https://www.python.org/ftp/python/3.6.0/python-3.6.0-embed-win32.zip
Due to some Internet limitations CMD cannot access and download files from the internet. Is it possible to feed the zip file manually?

**Comment by takluyver** [comment]
It's not really a feature, but if you find the cache location it would save the zip file to, and put it there manually, it should find it.

**Comment by takluyver** [comment]
On Windows, it's probably something like `C:\Users\You\AppData\Local\pynsist\{filename}`

**Comment by BerciMihai** [comment]
Thans, That worked, but now i get an error saying "Could not find BS4". I tried pip installing Beautifulsour4.6 in my python folder, and in the c:/users/user/appdata/local/programs/python/python3.6-32/lib but i still get the err

**Comment by BerciMihai** [comment]
Now I'm stuck with "ImportError: namespace packages do not have loaders"

**Comment by takluyver** [comment]
Can you show the traceback? Do you know what package it's looking for?

**Comment by BerciMihai** [comment]
`Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python27\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python27\Scripts\pynsist.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\nsist\__init__.py", line 540, in main
    InstallerBuilder(**args).run(makensis=(not options.no_makensis))
  File "c:\python27\lib\site-packages\nsist\__init__.py", line 495, in run
    self.prepare_packages()
  File "c:\python27\lib\site-packages\nsist\__init__.py", line 381, in prepare_packages
    py_version=self.py_version, exclude=self.exclude)
  File "c:\python27\lib\site-packages\nsist\copymodules.py", line 224, in copy_modules
    mc.copy(modname, target, exclude)
  File "c:\python27\lib\site-packages\nsist\copymodules.py", line 113, in copy
    loader = importlib.find_loader(modname, self.path)
  File "c:\python27\lib\importlib\__init__.py", line 104, in find_loader
    name=name)
ImportError: namespace packages do not have loaders`

**Comment by takluyver** [comment]
What does your `installer.cfg` contain? Can you try removing packages from the `packages=` list one by one to see which one it's having a problem with?

**Comment by takluyver** [comment]
Closing as I don't think there's anything to fix here.

Feel free to keep using the comments here for help & debugging. If you think there's an bug in Pynsist (there may well be some with namespace packages), or you want to ask a fresh question, you can open a new issue.
