### ISSUE TITLE
Pynsist + Basemap - ImportError: no module named '_geoslib'

### ISSUE THREAD

**Issue by luisdelatorre012** [takluyver/pynsist#128]
I have no idea if this is appropriate to post on here. I've also asked it as a question on [stackoverflow ](https://stackoverflow.com/questions/46433930/pynsist-basemap-importerror-no-module-named-geoslib) the pynsist tag has hardly been used, so I'm posting it here also.

I'm trying to use pynsist with basemap. I'm starting with the pynsist 'Guess the Number' example. I'm on Windows, using python 3.5.1.

Creating the program with `pynsist installer.cfg` and installing it work fine, but when I try to run the installed program I get `ImportError: No module named ...` for various modules. I added modules to the `[Include]` section of `installer.cfg` to fix these import errors. After adding these modules, the include section of `installer.cfg` is
```
[Include]
packages=guessnumber
    mpl_toolkits
    matplotlib
    six
    numpy
    pyparsing
    cycler
    dateutil
```
With these, I still get the error `ImportError: No module named '_geoslib'` when I run the installed program.

What am I doing wrong?

The only modifications I've made to the `guessthenumber` example are

1. the `[Include]` section of `installer.cfg` shown above
2. adding `from mpl_toolkits.basemap import Basemap` to the top of guessnumber.py

**Comment by cachitas** [comment]
Looks like you are missing a dependency (`pynsist` requires that you list all of them). 

[From the Basemap docs](https://matplotlib.org/basemap/users/installing.html) there is a dependency in GEOS that my be the cause of this missing DLL. I would try using the [Basemap wheel by Christoph Gohlke](http://www.lfd.uci.edu/~gohlke/pythonlibs/#basemap) (get also its dependecy `pyproj` from the same page). Then, extract the package from the wheel into the folder `pynsist_pkgs` as explained in the [docs](http://pynsist.readthedocs.io/en/latest/faq.html):

> Get the importable packages/modules, either from a Windows installation, or by extracting them from an installer. Copy them into a folder called pynsist_pkgs, next to your installer.cfg file. Pynsist will copy everything in this folder to the build directory.

**Comment by takluyver** [comment]
It's totally fine to ask questions like that here. :-) I try to keep an eye on SO as well, but I don't see things there as quickly.

I think @cachitas is probably right about a missing dependency and the best way to tackle that. I suspect that there might be some more complications down the road to do with the GEOS C library, but we'll deal with those as and when they come up.

**Comment by luisdelatorre012** [comment]
Thanks!

I'm not clear how to **extract the package from the wheel.** I previously used the wheel you suggested to install basemap. In a fresh virtualenv install, I see basemap in three places:
- Lib\site-packages\mpl_toolkits\basemap 
- Lib\site-packages\basemap-1.1.0.dist-info
- Lib\site-packages\basemap-1.1.0-py3.5-nspkg.pth

What exactly am I putting in the folder `pynsist_pkgs`?

**Comment by cachitas** [comment]
You can think of the `.whl` file as a `.zip` file. Just unzip it using your favorite tool. Inside every `mypackage.whl` you shall find a folder named `mypackage` among others. Copy the folder `mypackage` to `pynsist_pkgs`.

**Comment by takluyver** [comment]
Depending on what tools you have installed, it may be necessary to rename the wheel file so it has a `.zip` extension.

**Comment by luisdelatorre012** [comment]
After extracting the basemap 1.1.0 wheel into pynsist_pkgs, I no longer get the error ``ImportError: No module named '_geoslib'``, but now get another import error that I wasn't getting before:

```
ImportError: No module named 'mpl_toolkits.axes_grid1'
```

Stumped here. Googling this error says that matplotlib needs to be updated, but I'm using matplotlib 2.0.2, the latest stable build on pypi. I can't find a wheel for the AxesGrid matplotlib toolkit, so I can't apply the same fix you suggested for basemap.

**Comment by takluyver** [comment]
Might be namespace package issues. In your application's install directory (normally under Program Files), have a look in the `pkgs` folder, and the `mpl_toolkits` folder inside that. What does it contain?

**Comment by luisdelatorre012** [comment]
Ah, looks like some files are missing. Its only subfolder is basemap, and has no other files. 

Comparing this to the mpl_toolkits folder in my python install, that folder has 

```
__init__.py
__pycache__
axes_grid
axes_grid1
axisartist
basemap
exceltools.py
gtktools.py
mplot3d
```

So how do I fix this?

**Comment by takluyver** [comment]
Ugh, namespace packages. :-/

Can you describe what you've got at the moment? What's the full contents of `installer.cfg`, and what is there in `pynsist_pkgs`?

Have you tried with basemap extracted into `pynsist_pkgs` and matplotlib listed in `pypi_wheels`? What error does it give you in that case? And what ends up in `mpl_toolkits` like that?

**Comment by luisdelatorre012** [comment]
Well, I'm no longer getting any errors with `pypi_wheels= matplotlib==2.0.2` in installer.cfg. I could have sworn yesterday that this didn't fix the problem.

Thank you both for your help!

Here's the working [installer.cfg](https://gist.github.com/luisdelatorre012/5ebceaf27a25866e7cad91a5ffe43535).

**Comment by takluyver** [comment]
Thanks; I'm glad you've got it working!
