### ISSUE TITLE
import errors using wheels with namespace (ruamel.yaml)

### ISSUE THREAD

**Issue by albertogomcas** [takluyver/pynsist#133]
I have recently migrated from 1.11 to 2.0. 

Before 2.0:
- I had the decompressed ruamel.yaml in a folder pynsist_pkgs/ruamel/yaml/[lots of files]
- my include section in the .cfg had a ruamel.yaml entry
- the installer created a pkgs/ruamel/yaml[lots of files] folder in the installation path
- my application code used import ruamel.yaml as yaml
- and everything worked

In 2.0 I want to use the custom wheel sources, therefore I have:
- the ruamel.yaml wheel inside a folder wheels/ruamel.yaml-0.15.xxx.whl
- my include section in the .cfg has a ruamel.yaml entry, as well as extra_wheel_sources = wheels
- the installer creates a pkgs/ruamel/[empty!] folder and a pkgs/ruamel.yaml/[lots of files] folder in the installation path
- my aplication code uses import ruamel.yaml as yaml
- and I get import errors :(

I suspect the namespace is confusing somehow the creation of the pkgs folder of pynsist?

**Comment by takluyver** [comment]
It looks like it's working correctly when I specify `pypi_wheels = ruamel.yaml==0.15.34`. Can you show your .cfg file?

**Comment by albertogomcas** [comment]
```
[Application]
name = PieceWise
version = 0.5.3
entry_point = piecewise:main
icon = piecewise/ui/icon/PieceWise.ico

[Python]
version = 3.6.0
bitness = 64
format = bundled
include_msvcrt = True

[Include]
packages = piecewise
	peewee
	wrapt
	click
	ruamel.yaml

extra_wheel_sources = wheels

pypi_wheels = sip==4.19
	PyQt5==5.7.1

files = resources/
    README.rst
    LICENSE
    HISTORY.rst
```

**Comment by takluyver** [comment]
Try putting `ruamel.yaml==0.15.whatever` into `pypi_wheels`. Despite the name, pypi_wheels gets wheels from `extra_wheel_sources` as well.

**Comment by takluyver** [comment]
(And remove it from `packages=`)

**Comment by albertogomcas** [comment]
That fixed it, thank you!

**Comment by takluyver** [comment]
Great. I'll have a look at the docs to see if I can make it clearer.
