### ISSUE TITLE
Install location change from 1.x to 2.x

### ISSUE THREAD

**Issue by beardypig** [takluyver/pynsist#139]
It seems that the installation location has changed in 2.0, applications are installed to `Users\%USER%\AppData\Local\` instead of `Program Files`. Is it possible to change this behaviour in 2.0?

**Comment by takluyver** [comment]
If the user has admin rights, they should see a choice between installing for all users and just for themselves. If they choose to install for all users, it should go in program files just like before. If they install only for their own user, it goes in the user folder.

This uses the [MultiUser.nsh](http://nsis.sourceforge.net/Docs/MultiUser/Readme.html) script.

**Comment by beardypig** [comment]
Thanks, you're right. Totally our bad, we are overriding the `ui_pages` block and didn't include `!insertmacro MULTIUSER_PAGE_INSTALLMODE`. :)

**Comment by takluyver** [comment]
Not entirely your bad - maybe I could have thought more carefully about people using custom templates, but it's tricky to evolve Pynsist itself without breaking that interface.

**Comment by beardypig** [comment]
Well it might be useful to be able to change some of the `MULTIUSER` variables, like being able to `!undef MULTIUSER_INSTALLMODE_DEFAULT_CURRENTUSER` before `MultiUser.nsh` is loaded.

**Comment by takluyver** [comment]
Do you want to make a PR introducing a new block?

**Comment by beardypig** [comment]
Something like tjis 4f2996196dae7594fe286530a7270a0d4f0d57f6 ?

**Comment by takluyver** [comment]
Yup, exactly. I'd call it something like `multiuser_defs`
