### ISSUE TITLE
Use https with certificate validation to download Python

### ISSUE THREAD

**Issue by takluyver** [takluyver/pynsist#15]
We currently validate the downloaded MSI using gpg, but this is not ideal - users may not have GPG set up, especially on Windows, and we have to add some public keys to the user's keyring, which is not ideal.

Using https would be more portable. Python's urllib doesn't do any certificate validation by default, but the `requests` library does.

**Comment by JeremyRand** [comment]
Can GPG validation be re-added?  There's nothing wrong with having TLS in addition, but TLS relies on online keys, whereas GPG typically uses offline keys, which are much less likely to be compromised.  It's fine if it's optional for users who don't have GPG installed, but removing a security feature completely is unfortunate.
