### ISSUE TITLE
Unlaunchable "Desktop App" in start menu

### ISSUE THREAD

**Issue by olehermanse** [takluyver/pynsist#150]
I set up a project very similar to the example pyglet app. After installing, a shortcut shows up in "Recently added", which works. However when searching, a "Desktop App" (with the correct name of my project) shows up, and nothing happens when I click this. Anyone know where this comes from or why it does nothing? See gif:

![nsist](https://user-images.githubusercontent.com/4048546/38784060-89bdd966-410c-11e8-8a1f-932b2ab09178.gif)

I can't seem to find any logs in appdata either.

**Comment by olehermanse** [comment]
I tried:

 * Running this repair command I found in various tutorials: `DISM /Online /Cleanup-Image /CheckHealth`
 * Rebooting

And now the desktop app shortcut also works correctly. I have no clue what explains the previous weirdness.

**Comment by takluyver** [comment]
Mysterious. If it happens again, I would try:

- Right click on the item and see if you can get any more details on it
- Explore in 'all programs' to see if there are two entries.

**Comment by takluyver** [comment]
Closing for now because it seems to have been a one-off, and it's not clear what caused it. We can reopen the issue if it crops up again.
