### ISSUE TITLE
exclude option with pypi_wheel

### ISSUE THREAD

**Issue by ebranlard** [takluyver/pynsist#168]
I don't seem to get the exclude option to work with a package defined using pypi_wheel. This seems to have been implemented in #147 though.
The folder listed in the `exclude` statement is still shipped with the application. 

Here's my test, a file Hello.py:
```
import numpy
def fun():
    print(numpy.linspace(0,1,2))
```
A file installer.cfg:
```
[Application]
name=hello
version=0.1
entry_point=hello:fun
[Python]
version=3.7.0
[Include]
pypi_wheels = 
     numpy==1.15.2
exclude=pkgs/numpy/tests
```
I'm using python 3.7 [MSC v.1914 64 bit] on windows 10, and I cloned the latest pynsist. 

The exclusion works when using `package=numpy` instead of `pypi_wheels=`.

**Comment by takluyver** [comment]
Yes, it should work. Can you try to dig into what's going on? Maybe add a failing test for it?
