### ISSUE TITLE
Issue with inclusion of the SALib package wheel

### ISSUE THREAD

**Issue by breisfeld** [takluyver/pynsist#201]
Hi,
I am using python 3.7.7 and able to install a needed library, SALib, using the following command:

```
$ pip install SALib==1.3.11
```

I have created an `installer.cfg` file for `pynsist` that contains a requirement for this same version of python 

```
[Python]
version=3.7.7
```
and have also included the relevant line for the package: 

```
[Include]
pypi_wheels= SALib==1.3.11
...
```

When I execute

```
$ pynsist installer.cfg
```

I get the following error:

```
...
  File "c:\users\xxx\anaconda3\envs\popkat-env2\lib\site-packages\nsist\wheels.py", line 147, in get_from_pypi
    raise NoWheelError('No compatible wheels found for {0.name} {0.version}'.format(self))
nsist.wheels.NoWheelError: No compatible wheels found for SALib 1.3.11
```

No errors are raised for any of the other 21 packages in the `pypi_wheels` list.

Any clues about the cause?
Is there anything in the query to the PyPI repository that is causing this?

Thanks. 

Kind regards,
Brad

**Comment by takluyver** [comment]
Hi Brad. It appears that SALib doesn't currently publish wheels, so pip is installing it from a source distribution (i.e. compiling it on your computer). So far, Pynsist can't do this for you. You can create a wheel locally by running `pip wheel SALib==1.3.11` and then use the `extra_wheel_sources` or `local_wheels` option in the config file ([docs](https://pynsist.readthedocs.io/en/latest/cfgfile.html#include-section)) to use that.

**Comment by breisfeld** [comment]
Hi Thomas,

Thank you for the prompt and helpful response! I'll proceed with your suggestion.

Kind regards,
Brad
