### ISSUE TITLE
Docs: Example applications links broken

### ISSUE THREAD

**Issue by np-8** [takluyver/pynsist#214]
In the [documentation](https://pynsist.readthedocs.io/en/latest/examples.html) page, there are few broken links / removed examples
- A tkinter application
- A PyQt4 application
- A PyGTK application
- PyGTK with Numpy and Matplotlib (32 bit, Python 2.7)

**Comment by takluyver** [comment]
Thanks, good catch. Those examples were removed when Pynsist 2.0 dropped support for Python 2.7 and running the Python.org installer (now we use the embeddable Python build instead).

Do you want to make a PR to remove them from the list?

We could leave a note underneath to mention that Pynsist 1.x also had examples for PyGTK and PyQt4. I'm in two minds - it's obviously helpful to mention that it's possible if people are using those frameworks, but I don't want to imply that it's still supported or receiving bugfixes.

**Comment by np-8** [comment]
Here you are!  Fast fix. Maybe it's better that you or anyone more familiar with the framework and its history gives the possible notes for PyGTK / PyQt4.

**Comment by takluyver** [comment]
Thanks!
