### ISSUE TITLE
Setuptools integration

### ISSUE THREAD

**Issue by takluyver** [takluyver/pynsist#22]
@jbaiter wrote on PR #13:

"""
I'm currently preparing to ship [spreads](https://github.com/DIYBookScanner/spreads) for Windows. The software makes heavy use of the Python packaging ecosystem for its plugin discovery, so I had to work around some small issues with pynsist to get it to package all of the `.egg-info` and `.dist-info` files/directories. You can take a look at the script that builds the MSI installers to see how I'm currently using pynsist from code: https://github.com/jbaiter/spreads/blob/windows/buildmsi.py

It would be great if setuptools/pkg_resources integration could be put on the roadmap, I think that's a feature that would benefit a lot of people and the ecosystem as a whole.
"""

@jbaiter's script finds and copies the egg-info/dist-info bits separately from the actual packages. I'm not sure at present whether it's easier to do that, or to treat 'distributions' as a different kind of thing, which include that info along with a number of packages.

**Comment by adferrand** [comment]
Something that could be closed as #161 is merged?

**Comment by takluyver** [comment]
Yup, thanks.

For people finding this in the future: Pynsist supports the standardised `.dist-info` metadata from wheel packages. I have no plans to support setuptools' pre-standardisation 'egg' formats.
