### ISSUE TITLE
building a project that has code in src directory

### ISSUE THREAD

**Issue by bfmcneill** [takluyver/pynsist#228]
I can't seem to figure out how to build a project where the package is in one directory below config file

```
src
    \
     guessnumber
```

Should I put the installer.cfg inside the src file or is there some way to configure installer.cfg to reach in one level?

**Comment by takluyver** [comment]
It finds the package like an import (`import guessnumber`). So you can install it locally in the same Python environment as Pynsist, or set the environment variable PYTHONPATH=src/ while running Pynsist, or anything else that would make it importable.

I probably wouldn't design it this way now, but it is what it is.
