### ISSUE TITLE
Fix simple typo: conists -> consists

### ISSUE THREAD

**Issue by timgates42** [takluyver/pynsist#229]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate

1. Examine examples/pygi_mpl_numpy/pygi_test.py.
2. Search for `conists`.

# Expected Behaviour

1. Should read `consists`.

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/pynsist/pull/new/bugfix_typo_consists

Thanks.

**Comment by takluyver** [comment]
Meticulous indeed! :laughing: I've never had a pull request request before. Please do feel free to open the PR; I dare say the CI will cope.

**Comment by timgates42** [comment]
Thanks @takluyver added #230
