### ISSUE TITLE
How to ship CLI and GUI of same application together?

### ISSUE THREAD

**Issue by wxguy** [takluyver/pynsist#232]
My application has a support for both Command Line and Graphical User Interface. When the user enter application name without argument, then the GUI is launched and if arguments are provided, then it works as CLI. Is there a way to include these two features together with Pynsist?

**Comment by takluyver** [comment]
You can include a command by adding a [command section](https://pynsist.readthedocs.io/en/latest/cfgfile.html#command-sections) to the `installer.cfg` file. The command calls a Python function (usually something like `main()`), which can do whatever you want.

You'll also get at least one start menu shortcut. The preferred way to define this is also pointing to a Python function. It sounds like in your case the shortcut can point to the same function as the command, so it's equivalent to running the command with no arguments.
