### ISSUE TITLE
create single file exe installer

### ISSUE THREAD

**Issue by Eliav2** [takluyver/pynsist#241]
is this possible to use this library to create a single file exe installer?

I will explain - I built a GUI tk application, I can use pyinstaller to build dest folder (with exe run and all dependencies inside), then archive it as a zip, and then use [nsis](https://nsis.sourceforge.io/Download) to create single file installer based on this zip.

so, is it possible to use this lib and create a single file installer similarly?

**Comment by takluyver** [comment]
If you really mean an installer - an exe you run to install the application - then yes, that's what Pynsist is for.

When people talk about 'single file' in this context, they usually mean an exe file that runs the application directly, without needing to install it. This usually works by extracting files to a temporary folder and then running the application from there. Pynsist *doesn't* do this, but [it is an option in Pyinstaller](https://pyinstaller.readthedocs.io/en/stable/operating-mode.html#bundling-to-one-file).

**Comment by Eliav2** [comment]
no - I mean actually a single file installer for installing the application (that could be installed as a folder with many files), I don't mean creating single file exe for running the application, but a single file installer that can install the app

**Comment by takluyver** [comment]
OK, in that case, yes, that is what Pynsist gives you (or tries to).

**Comment by Eliav2** [comment]
But the build folder has many files except the installer, you say only the Eze installer is necessary?

**Comment by takluyver** [comment]
Yup, sorry for any confusion - it uses those files to produce the installer, but the installer should then work by itself.

**Comment by Eliav2** [comment]
Thank you
