### ISSUE TITLE
Start menu shortcut directory

### ISSUE THREAD

**Issue by infinitepower18** [takluyver/pynsist#244]
Hi, thank you for this tool. It's really helpful.

I was wondering if there is a way to change the working directory for the start menu shortcut to the installation directory. Due to some complications, I would like to make it use the installation directory instead of %HOMEDRIVE%%HOMEPATH%.

Currently I would have to run this tool to generate the installer file, manually edit the nsi file to use the installation directory instead for the start menu shortcut and then compile it through NSIS. Can this be done in pynsist itself without having to go through all this?

**Comment by takluyver** [comment]
Sorry, there's nothing in Pynsist for that. You can call `os.chdir()` as the first thing in the main function it runs when launching your application, if you need. But I think in general, code should avoid assuming a particular working directory.

See in the docs:

- [Installer details -> Working directory](https://pynsist.readthedocs.io/en/latest/installers.html#working-directory)
- [FAQs -> Using data files](https://pynsist.readthedocs.io/en/latest/faq.html#using-data-files)
- [Design principles -> If you need more flexibility](https://pynsist.readthedocs.io/en/latest/design.html#if-you-need-more-flexibility)
