### ISSUE TITLE
makensis not found

### ISSUE THREAD

**Issue by fzumstein** [takluyver/pynsist#25]
For whatever reason, NSIS doesn't register itself in the registry and so pynsist doesn't find it. I am on Windows 7, 64-bit.

**Comment by idleberg** [comment]
Sorry for bumping this old thread. Have you considered adding a `--makensis` flag that allows specifying a custom path to `makensis`?

**Comment by takluyver** [comment]
It now looks up `makensis` on PATH first, so if you want to specify a custom location, you can prepend the directory to that environment variable. That assumes that the executable itself is always called `makensis`.

If that doesn't fit your needs, feel free to make a PR. I'd probably call the option something like `--makensis-path`, to avoid having `--makensis` and `--no-makensis` which aren't symmetric.
