### ISSUE TITLE
cannot reach localhost:8501

### ISSUE THREAD

**Issue by OuOLeaf** [takluyver/pynsist#255]
Thanks to your tips, I have already installed execution of streamlit.
However, whenever I open it, it always shows this kind of error.
Could you give me some advice?

**Comment by takluyver** [comment]
Not a lot of advice, but that probably means that the server part of streamlit hasn't started successfully, so your browser is trying to talk to something that's not there. There might be more details of any errors in the log file - see: https://pynsist.readthedocs.io/en/latest/installers.html#logging-output
