### ISSUE TITLE
Remove the necessity of copying all modules for every build

### ISSUE THREAD

**Issue by raphaelm** [takluyver/pynsist#33]
First of all, thanks for this cool project.

In my build process, it is a major slow-down that all the (globally installed) packages like PySide or Django are being copied every time which can take minutes.
Do you see a possibility of avoiding this in an intelligent way (such that my own packages are still being copied every time)? I'm totally fine with some manual command line parameter like ``--skip-copying=PySide`` if I'm certain that PySide has not been updated since the last build.

**Comment by raphaelm** [comment]
Well, let's close this. I recently built my VirtualBox setup from scratch and combined with the ``exclude`` option its now reasonable fast. Not copying all files will be hard, because we can't know what to copy and what not (and, for a big number of small files, comparing all files won't be faster than copying all).

**Comment by takluyver** [comment]
OK, glad it's working better for you now.
