### ISSUE TITLE
Excluding files from include not working

### ISSUE THREAD

**Issue by aaren** [takluyver/pynsist#39]
I'm trying to use the `exclude` feature in the `[Include]` section of the config file but I can't get it to work.

I've created a really simple app to test this:

```
installer.cfg
app/__init__.py
app/main.py
ext/__init__.py
ext/ignored/binary
ext/ignore.py
```

`installer.cfg` contains:

``` cfg
[Application]
name=App
version=1.0
entry_point=app.main:main
console=false

[Python]
version=2.7.8

[Include]
# Importable packages that your application requires, one per line
packages = app
    ext

exclude = pkgs/ext/ignored
    pkgs/ext/ignore.py
```

I am expecting `ext/ignore.py` and the contents of the directory `ext/ignored` to not be copied to `build/nsis/pkgs`, but they are.

I looked at the copying code in [nsist.copymodules.ModuleCopier](https://github.com/takluyver/pynsist/blob/90ded5ddbf49cca3f356025b665ef177951e0401/nsist/copymodules.py#L160-L208) but can't see exactly what might be wrong.

I put in some prints before and after the for loop in [nsist.copymodules.copytree_ignore_callback](https://github.com/takluyver/pynsist/blob/90ded5ddbf49cca3f356025b665ef177951e0401/nsist/copymodules.py#L68-L86):

``` python
    print 'excludes: ', excludes
    print 'files: ', files
    print 'fnmatch: ', [fnmatch.filter(files, pattern) for pattern in excludes]
    # Execute all patterns
    for pattern in excludes + ['*.pyc']:
        ignored.update([
            os.path.basename(fname)
            for fname in fnmatch.filter(files, pattern)
        ])

    print 'ignored: ', ignored
    return ignored
```

and now get the following output on running `pynsist installer.cfg`:

```
excludes:  [u'pkgs/ext/ignored', u'pkgs/ext/ignore.py']
files:  [u'pkgs/app\\.\\main.py', u'pkgs/app\\.\\__init__.py']
fnmatch:  [[], []]
ignored:  set([])
excludes:  [u'pkgs/ext/ignored', u'pkgs/ext/ignore.py']
files:  [u'pkgs/ext\\.\\ignore.py', u'pkgs/ext\\.\\ignored', u'pkgs/ext\\.\\__init__.py']
fnmatch:  [[], []]
ignored:  set([])
excludes:  [u'pkgs/ext/ignored', u'pkgs/ext/ignore.py']
files:  [u'pkgs/ext\\ignored\\binary']
fnmatch:  [[], []]
ignored:  set([])
```

It looks like this is something to do with `fnmatch.filter` but I'm not sure yet.

I'm using Windows 7 with Anaconda with Python 2.7.8 and pynsist installed via pip.

**Comment by takluyver** [comment]
I guess we might need to do some path normalisation to deal with / vs \.
