### ISSUE TITLE
Glib schemas in pygi example need updating before packaging the application

### ISSUE THREAD

**Issue by takluyver** [takluyver/pynsist#43]
@tobias47n9e found that opening a file dialog causes an error unless you run `glib-compile-schemas` in the correct directory beforehand (tobias47n9e/innsbruck-stereographic#1).

The `glib-compile-schemas` command also exists on my Linux system. Are the results it generates compatible with Windows? It updates a binary file called `gschemas.compiled`. Running md5sum:

```
9a8d488336f63ba3c3e3add8b1a8550d   gschemas.compiled as extracted from the pygi Windows bundle (3.14.0_rev13)
3a0a39219a8ca06cbdac77804a771908  gschemas.compiled from running `glib-compile-schemas` on Debian.
```

@tobias47n9e , what's the md5sum of that file after running `glib-compile-schemas` on Windows? It's a long shot that it would be exactly the same, but you never know.

Assuming it's not, we should look into what it does. It may be that it's usable even if the file isn't bit-for-bit identical. Or we may be able to write a Python script that emulates its Windows behaviour somehow.

**Comment by takluyver** [comment]
gschemas.compiled appears to be a 'GVariant database'. I can't find any documentation of that format, but the code to read it is [here](https://git.gnome.org/browse/gvdb/tree/), and the code for glib-compile-schemas is [here](https://github.com/GNOME/glib/blob/master/gio/glib-compile-schemas.c).

**Comment by tobias47n9e** [comment]
It looks like the 64-bit Windows file and your Debian file match up.

```
compiled on 32-bit Windows (using the pygi installer):
0ff9699c6b86bb1e0b4d527a252ceb79

compiled on 64-bit Windows (using glib-compile-schemas share\glib-2.0\schemas)
3a0a39219a8ca06cbdac77804a771908
```

**Comment by takluyver** [comment]
Aha, that's promising. So compiling on Linux should work, at least if your system is the same bitness as you want to target. It might still be readable if the bitness doesn't match, but I won't be able to test a 32 bit application on my Windows VM for a couple of weeks now.

Do you want to add `compile-glib-schemas` to the extract script, along with a note in the README about our suspicions with regard to bitness?

**Comment by tobias47n9e** [comment]
By the way: Did you also get these warnings on Linux:

```
warning: Schema 'org.gnome.system.locale' has path '/system/locale/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
warning: Schema 'org.gnome.system.proxy' has path '/system/proxy/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
warning: Schema 'org.gnome.system.proxy.http' has path '/system/proxy/http/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
warning: Schema 'org.gnome.system.proxy.https' has path '/system/proxy/https/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
warning: Schema 'org.gnome.system.proxy.ftp' has path '/system/proxy/ftp/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
warning: Schema 'org.gnome.system.proxy.socks' has path '/system/proxy/socks/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.

```

**Comment by tobias47n9e** [comment]
https://github.com/takluyver/pynsist/pull/44

**Comment by takluyver** [comment]
Nope, I don't see those warnings.
