### ISSUE TITLE
Add example to API documentation

### ISSUE THREAD

**Issue by tobias47n9e** [takluyver/pynsist#56]
Currently the documentation reads:

> shortcuts (list) – Dictionary keyed by shortcut name, containing dictionaries whose keys match the fields of Shortcut sections in the config file

I don't understand this sentence at all and I have the feeling that this function also has a different behaviour than what the documentation says:

https://github.com/takluyver/pynsist/blob/master/nsist/__init__.py#L268

> Either entry_point, script or target must be specified, but not more than one. Specifying entry_point is normally easiest and most reliable.

I also don't think passing a list works.

This is how I thought it would work:

 ```python
appname = "InnStereo"
version = "beta3"
shortcuts = {"entry_point": "innstereo:startup",
             "extra_preamble": "gnome_preamble.py",
             "console": "false"}
icon = "innstereo_icon.ico"
icon_path = os.path.abspath(os.path.join(os.path.dirname(__file__), icon))
pkg_list = ["innstereo", "gi", "cairo", "dbus", "gnome", "pygtkcompat",
            "numpy", "matplotlib", "six", "dateutil", "pyparsing", "scipy",
            "mplstereonet"]
inst_name = "InnStereo {}".format(version + " {}")

installer64 = nsist.InstallerBuilder(appname, version, shortcuts,
                                     icon=icon_path,
                                     packages=pkg_list,
                                     extra_files=None,
                                     py_version="3.4.3",
                                     py_bitness=64,
                                     py_format="installer",
                                     build_dir="build/nsis",
                                     installer_name=inst_name.format("64bit"),
                                     nsi_template=None,
                                     exclude=None)

installer64.run()

```

But it shows this backtrace:

```
  File "make_win.py", line 78, in <module>
    installer64.run()
  File "/usr/lib/python3.4/site-packages/nsist/__init__.py", line 428, in run
    self.prepare_shortcuts()
  File "/usr/lib/python3.4/site-packages/nsist/__init__.py", line 279, in prepare_shortcuts
    if not sc.get('target'):
AttributeError: 'str' object has no attribute 'get'
```

I think the documentation should show a minimal working example of how to initalize the ```nsist.InstallerBuilder()```-class. Thank you for your help!

**Comment by takluyver** [comment]
I think you need to wrap your shortcut definition in a list (after all, there could be more than one shortcut):

```python
shortcuts = [
    {"entry_point": "innstereo:startup",
     "extra_preamble": "gnome_preamble.py",
     "console": "false"},
]
```

I'll try to clarify the wording for that.

**Comment by takluyver** [comment]
Also, `"false"` will probably need to be `False`, the boolean value. Ninja editing my previous comment.

**Comment by takluyver** [comment]
No, hang on, the description is right, it's a dict of dicts. The key at the top level is the name that the shortcut will have:

```python
shortcuts = {"InnStereo":
    {"entry_point": "innstereo:startup",
     "extra_preamble": "gnome_preamble.py",
     "console": False},
}
```

**Comment by tobias47n9e** [comment]
Thank you very much for the explanation and example!

**Comment by takluyver** [comment]
You're welcome!

I'm still not very pleased with the description I've written for that parameter, but I'm not sure how much clearer it can be without making it a lot longer, which I'd rather avoid.

**Comment by tobias47n9e** [comment]
For me this sentence would have worked better:

Dictionary keyed by **the app's** shortcut name, containing dictionaries whose keys match the fields of Shortcut sections in the config file

**Comment by takluyver** [comment]
I think that makes it less clear that one app can have multiple shortcuts, though. In the config file, the `[Application]` section defines one shortcut, and you can use `[Shortcut ...]` sections for extra shortcuts, but the Python API doesn't treat any one shortcut differently from the others.

**Comment by tobias47n9e** [comment]
That is right. I forgot about that. In any case people confused about the usage will probably now be able to find this thread.
