### ISSUE TITLE
Missing msvcp140.dll when using PyQt with bundled Python 3.5

### ISSUE THREAD

**Issue by takluyver** [takluyver/pynsist#58]
Ping @zooba - we're having some trouble with building PyQt apps with the embeddable Python 3.5 builds, and it looks like the issue is with the MSVC runtime again.

I'm seeing this, for example, on my Windows 8 installation. ucrtbase.dll is already present, so the installer doesn't try to download and install the MSVC 2015 MSU. But then, when the code tries to load PyQt, it fails because msvcp140.dll is missing. [This SO question](http://stackoverflow.com/questions/34727256/bundling-a-pyqt4-application-with-pynsist) is someone having the same problem on Windows 10, where I thought that the MSVC 2015 runtime was already installed. :confused: 

I don't understand how the different pieces of the MSVC runtime relate to each other. We have:

- ucrtbase.dll : installed in `C:\Windows\System32`; present by default (hopefully) on Windows 10, part of the 'redistributable' download for Windows Vista to 8.1.
- vcruntime140.dll: shipped with the Python embeddable builds.
- msvcr140.dll: ? (I thought these bits went along with ucrtbase, but seemingly not)
- msvcp140.dll: ?
- other bits?

What are all these pieces for?

Should I be checking for some/all of the msvc*140.dll files as well as ucrtbase.dll to decide whether to install the redistributable MSUs? If so, is there an MSU I can use for Windows 10? Currently I only have MSUs for up to Windows 8. Or should these files be installed as part of the application?

**Comment by zooba** [comment]
`msvcp140.dll` is the C++ runtime. It isn't a Windows component (like `ucrtbase.dll`), so it isn't in the MSU - you'll need to install the full vcredist package in this case.

Though IMHO, `msvcp140.dll` should be bundled with PyQt, as it is apparently a dependency of that package. `vcruntime140.dll` is a dependency of Python, which is why it is included with Python.

Other potential dependencies can be found in `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\x86` and `x64` (if you have VS 2015 installed).

**Comment by takluyver** [comment]
OK, it sounds like it makes most sense to package it with PyQt. Unfortunately it doesn't come with PyQt (at least the download that I got). Is there a canonical location to download it? It looks like I can get it out of the vcredist installer with a bit of trickery, but it looks like the Microsoft download website tries to prevent automated downloads. Do I need to extract it and stick it on Github as I do with the MSUs? Will it need any of the other DLLs that are packaged with it?

**Comment by zooba** [comment]
It's easiest to get it from a VS or VC install, and ideally it should come from the same version that was used to build it. If you're going to extract it from the installer, you may as well just run the installer and copy it from your system directory. There may be licensing issues with having the files checked into a project, but I doubt anyone will go after you for that - things are getting a lot more pragmatic here wrt these sorts of essential dependencies.

AFAICT, `msvcp140.dll` only requires the CRT, but depending on what features are used it may require `concrt140.dll` (the concurrency runtime). They're both part of vcredist, so they should appear together.

**Comment by takluyver** [comment]
I want to be able to produce installers from Linux - this is a key feature of Pynsist - so I'd ideally like to script a way to extract the DLL directly. It looks like this is possible using `cabextract`.

What are the possible consequences of it not being the version that was used to build PyQt? I'm using prebuilt binaries, so I don't know the details of how they were built.

**Comment by zooba** [comment]
In theory there shouldn't be any breaking changes made without changing the filename, so it should be okay. But any bugfix has the chance of changing behaviour, and if PyQt is relying on that change it could break in unexpected ways that are going to be pretty hard to diagnose.

Really, it's just something to consider when strange bugs appear - don't assume that the runtime is the same one the original developers tested against.

**Comment by takluyver** [comment]
OK, I'll bear that in mind, but I think I'll try bundling the copy of msvcp140.dll from vcredist. I'd rather not compile Qt and PyQt myself. Thanks for your help once again.
