### ISSUE TITLE
Non-admin install

### ISSUE THREAD

**Issue by takluyver** [takluyver/pynsist#65]
Pynsist installers currently call `RequestExecutionLevel admin` and install into the system Program files folder. This was the normal way to do things when I was last a regular Windows user. However, many applications now offer per-user installation, which doesn't require admin rights. It [looks like](https://msdn.microsoft.com/en-us/library/windows/desktop/dd378457%28v=vs.85%29.aspx#FOLDERID_UserProgramFiles) the convention is to install into `%LOCALAPPDATA%\Programs`.

Should this be an option the application developer picks, or a choice offered to the user? Intuitively, it seems like a user choice, but the installer exe has one manifest saying whether it should be run as admin or not, so I guess offering the user the choice at install time involves some extra complexity. There's an NSIS [MultiUser](http://nsis.sourceforge.net/Docs/MultiUser/Readme.html) header file that might be useful.

**Comment by Siecje** [comment]
What needs to happen for this to work?

If I set ```RequestExecutionLevel user``` the installer works as long as you don't select a directory that the current user cannot access (ex. Program Files). If you do select ```Program Files\``` it just fails silently.

The only problem is that the shortcut is not created. On Windows 10 with the current UAC installer the shortcut is created in ```C:\ProgramData\Microsoft\Windows\Start Menu\Programs\```. Without the shortcut there is nothing to double click and launch the application.

The .msi created by cx_Freeze (```bdist_msi```) doesn't require the UAC prompt when you launch it but it does after you select a path (even if that path is on your Desktop).

**Comment by takluyver** [comment]
I think the shortcuts would need `SetShellVarContext current` (in place of `all`) in the install and uninstall sections.

I think the best way to do this is with the [MultiUser](http://nsis.sourceforge.net/Docs/MultiUser/Readme.html) header file. That should make it possible for the user, rather than the developer, to select per-user or per-machine installation. It looks simple to use - follow the example under *Mixed-Mode Installation* - but will need quite a bit of testing.

**Comment by takluyver** [comment]
@Siecje Have a go with [this installer](https://www.dropbox.com/s/n0akzlldfw27gdz/Noisy_(Pyglet)_1.0.exe?dl=1), built with the code in PR #100.

**Comment by Siecje** [comment]
@takluyver That installer requested permission. The icon has the blue and yellow shield (same icon next to Run as Admin in context menu.

In the installer I selected install for me (the other option was install for all users) It installed into ```C:\Users\Cody\AppData\Local\Noisy (Pyglet)\Python```

**Comment by takluyver** [comment]
I've set it to request 'Highest' execution level. That means that if you're an admin user, it will try to run as admin and give you the option to install for all users, but it should be OK installing as a non-admin user. As far as I can tell, there isn't a way to request admin privileges only if the user selects an all-users install.

There's nothing to add to the config for this, you just recompile the app with the `multiuser` branch.

**Comment by takluyver** [comment]
(We could instead just do a per-user install always, never request admin permissions, and don't give the user the 'install for everyone' option. I'm considering that, but it seems weird to remove the option to install into 'Program Files', because that's the 'normal' install location)

**Comment by Siecje** [comment]
As a non-admin user I installed your installer but it was 64-bit so I couldn't run it.

I built the same application as 32-bit and installed it. It installed overtop of the previous installation. 

The install directory was
`C:\Users\notadmin\AppData\Local\Noisy (Pyglet)\`

**Comment by takluyver** [comment]
That sounds like it's working as intended :-)

**Comment by Siecje** [comment]
I believe since https://github.com/takluyver/pynsist/pull/100 was merged this can be closed.

**Comment by takluyver** [comment]
Yup, thanks for the reminder!
