### ISSUE TITLE
Workaround for Python 3.5 install

### ISSUE THREAD

**Issue by techtonik** [takluyver/pynsist#68]
I wonder if `pynsist` includes workaround for missing run-times for Windows for Python 3.5?

https://github.com/winpython/winpython/issues/341

**Comment by takluyver** [comment]
Yes, though it's not a bit of code I'm especially proud of. I have the .msu Windows update packages stored in a [separate branch](https://github.com/takluyver/pynsist/tree/msvcrt-2015-msus), and some [NSIS code](https://github.com/takluyver/pynsist/blob/master/nsist/pyapp_msvcrt.nsi) that tries to discover if the runtime is needed, and downloads the relevant package at runtime if so.

I should at a minimum change the downloads to use https://rawgit.com/ , which I didn't know about when I wrote that.

I'm told that Windows 10 already has the necessary runtime, so there's no need to install it there, and I think the official Python installers make sure it's installed. So Pynsist only checks for it if it's using the embeddable windows build (`format=bundled` in the Pynsist config file).

**Comment by techtonik** [comment]
I got report from user on Windows 8.1, so this is an actual problem. Do you think it is possible to port this functionality to official Python installer? Quick look reveals that it is probably here - https://hg.python.org/cpython/file/tip/Tools/msi

**Comment by takluyver** [comment]
I'm pretty sure the official Python installers already make sure that the C runtime is correctly set up. Certainly what I'm doing here is an order of magnitude more clumsy than the official Python.org installers. I think your user has run into the issue discussed here: http://bugs.python.org/issue25157

**Comment by techtonik** [comment]
Looking at the amount of people reported this issue, something is really broken on Windows Update side. Windows 7 users seem to be able to heal this with SP1, which is not installed by default (UX fail), and Windows 8.1 it looks like https://support.microsoft.com/en-us/kb/2919355 needs to be installed first.
