### ISSUE TITLE
Embeddable .zip versions of Python > 3.5

### ISSUE THREAD

**Issue by mfitzp** [takluyver/pynsist#70]
As of Python 3.5 there are now 'embeddable' versions of Python available for download e.g. see the bottom of [https://www.python.org/downloads/release/python-351/](https://www.python.org/downloads/release/python-351/) 

These are `.zip` archives of a complete Python install, but without the installer. It ships with `pythonw.exe`

Might it be possible to bundle this with the application (instead of an installer) and unpack into the target folder? Saves messing with the system Python on the target machine.

**Comment by takluyver** [comment]
Yes! This is already working, you just need to specify `format=bundled` in the Python section of the config file. I'm moving in the direction of doing that more, to produce simpler, more independent installers.

See the notes on this option in the docs: http://pynsist.readthedocs.io/en/latest/cfgfile.html#bundled-python
