### ISSUE TITLE
Issue with requests module

### ISSUE THREAD

**Issue by RomGutman** [takluyver/pynsist#73]
Hi,

While trying to run the installer.cfg, I'm encountering with an issue with the requests module, in which is unable to establish connection to the target site ( "https://www.python.org/ftp/python/2.7.10/python-2.7.10.msi").

I guess the issue occurs due to fact that I need to set a proxy connection in order to download/install/retrive content from external site (=outside of corp network)

how can I solve this problem?

this is the error:

```
Downloading Python installer...
Getting https://www.python.org/ftp/python/2.7.10/python-2.7.10.msi
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\lib\site-packages\nsist\__main__.py", line 2, in <module>
    main()
  File "C:\Python27\lib\site-packages\nsist\__init__.py", line 523, in main
    ).run(makensis=(not options.no_makensis))
  File "C:\Python27\lib\site-packages\nsist\__init__.py", line 451, in run
    self.fetch_python()
  File "C:\Python27\lib\site-packages\nsist\__init__.py", line 188, in fetch_pyt
hon
    download(url, cache_file)
  File "C:\Python27\lib\site-packages\nsist\util.py", line 26, in download
    r = requests.get(url, headers=headers, stream=True)
  File "C:\Python27\lib\requests\api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\requests\api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\requests\sessions.py", line 471, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\requests\sessions.py", line 579, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\requests\adapters.py", line 415, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='www.python.org', p
ort=443): Max retries exceeded with url: /ftp/python/2.7.10/python-2.7.10.msi (C
aused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPS
Connection object at 0x028E6B10>: Failed to establish a new connection: [Errno 1
0060] A connection attempt failed because the connected party did not properly r
espond after a period of time, or established connection failed because connecte
d host has failed to respond',))
```

**Comment by takluyver** [comment]
Looking at the [requests docs](http://docs.python-requests.org/en/master/user/advanced/#proxies), it appears there's an environment variable `HTTPS_PROXY` which you can set to tell requests about the proxy. [This site](http://www.computerhope.com/issues/ch000549.htm) has info about how to set environment variables in Windows, in case you're not familiar with them.

If that works, it seems like the neatest approach, because Pynsist doesn't currently have a way to configure things related to the computer it's running on.

**Comment by RomGutman** [comment]
Thank you for you quick answer! 
just to make sure, will it require also to set the env variable in each of the target computers? (=the ones that I want actually to install my app on)

again, thank you for the quick answer :)

**Comment by takluyver** [comment]
No, requests isn't involved in the install process, so you should only need it to be set on your machine where you make the installer.

Of course, if your *application code* makes HTTP requests (with the `requests` package or any other mechanism), you may need to do something extra to ensure it works on the target computer. Pynsist doesn't affect that, though.

**Comment by RomGutman** [comment]
Oh, that's great news, I thought the Pynsist requires downloading on the installation process :)

thank you very much!

**Comment by takluyver** [comment]
There is one situation where the installer can download something, but:

- That download uses NSIS' [Inetc plugin](http://nsis.sourceforge.net/Inetc_plug-in), which will automatically follow Windows' system proxy settings.
- That case can only occur with Python >= 3.5, and I see from your traceback that you're building an installer with Python 2.7.

So it's not a concern :-)
