### ISSUE TITLE
Still missing some part of MSVC runtime

### ISSUE THREAD

**Issue by takluyver** [takluyver/pynsist#75]
From discussion with @Siecje:

> I installed it on a Windows 7 machine and I noticed...
> It wouldn't start because "api-ms-win-crt-runtime-l1-1-0.dll" was missing.

@zooba, any idea what this file is? This should have been after the MSU package was installed, although it's possible there was some problem downloading it.

**Comment by zooba** [comment]
Yes, this is installed by the MSU. I'd have to assume that it didn't install properly - possibly waiting on a reboot? (Unfortunately the only signal you get from the MSU installer is the exit code, and those are not well documented :( )

**Comment by takluyver** [comment]
Thanks, it's good to know that this should be installed, so something's going wrong in Pynsist.

Looking back at the code, it does check for:
- Download failing, to display a message box.
- The exit code documented as meaning a reboot is needed (`0x00240005`), in which case the user is prompted with a yes/no question to restart after installing.

But I don't currently do anything on any other exit code.

**Comment by zooba** [comment]
There are a few more exit codes indicating a reboot is needed, but when the reboot is needed _before_ installing they are returned as errors. It's probably worth reporting any error code (`code & 0x80000000 != 0`) and suggesting a reboot if the update install fails.
