### ISSUE TITLE
pypi_wheels entry ignored

### ISSUE THREAD

**Issue by cachitas** [takluyver/pynsist#77]
Given our discussion in #30, I am playing around with `opencv-python` and found that `pynsist` is ignoring it. The `pkgs` folder only contains the `main.py` script.

Could it be the parsing of the name?

Please check [this gist](https://gist.github.com/cachitas/0da142af7da05c18b6b12a976415471c) to look at the installer.cfg and the console output.

**Comment by takluyver** [comment]
I can replicate this, but it's not ignoring the wheel; I think it's because the opencv-python wheels are in a bit of an odd format and Pynsist isn't unpacking them properly. I'll play around with it now.

**Comment by cachitas** [comment]
Thank you!
I thought it was being neglected because I could not find in the output any reference to the module.
Maybe it could be useful to add some warning message when something like this happens?

**Comment by takluyver** [comment]
The first time you do it, there should be some output saying "Downloading wheel". But after the first time, it has it cached so it doesn't need to download it again. It would be a good idea for it to fail if it doesn't unpack any files from the wheel, though.

**Comment by cachitas** [comment]
You are right, just checked that cleaning the cached module gives rise to the logged message. May I suggest adding a message also when the package is fetched from the cache, or would it add too much noise? Sounds simple to add, maybe I could give it a try.

**Comment by takluyver** [comment]
I don't think that would be too noisy, you're welcome to do a PR :-)
