### ISSUE TITLE
Unknown Publisher (UAC)

### ISSUE THREAD

**Issue by Siecje** [takluyver/pynsist#80]
When you run the installer .exe the User Account Control says the Publisher is Unknown.

Is it possible to list a company name there?

**Comment by takluyver** [comment]
I believe that requires signing the installer. As far as I know, all options for this cost money, but I found one that is only €14:

http://pynsist.readthedocs.io/en/latest/faq.html#code-signing

I haven't ever signed an installer myself, so if you do investigate this further, please let me know what you find.

**Comment by Siecje** [comment]
How do you sign the installer?

**Comment by takluyver** [comment]
See the link above. I don't know any more about it than that.

**Comment by takluyver** [comment]
Closing this now, but I'd be interested to hear if anyone successfully signs an installer.
