### ISSUE TITLE
Can't get variable to work in files section.

### ISSUE THREAD

**Issue by sbstp** [takluyver/pynsist#85]
```ini
files=../win32/streamlinkrc > $APPDATA\streamlink
      ../win32/rtmpdump > $INSTDIR
```
The `$APPDATA` variable doesn't work and gets erased. No issues with `$INSTDIR`.
This is what the `installer.nsi` file looks like:
```nsi
; Install files
  SetOutPath "$INSTDIR"
    File "glossyorb.ico"
    File "Streamlink.launch.pyw"
  SetOutPath "\streamlink" ; <---- Issue seems to be here
    File "streamlinkrc"
  SetOutPath "$INSTDIR"
    File "_system_path.py"
    File "_rewrite_shebangs.py"

; Install directories
  SetOutPath "$INSTDIR\Python"
  File /r "Python\*.*"
  SetOutPath "$INSTDIR\bin"
  File /r "bin\*.*"
  SetOutPath "$INSTDIR\rtmpdump"
  File /r "rtmpdump\*.*"
```

**Comment by takluyver** [comment]
That's strange. I've just tried and failed to reproduce it by changing one of the examples:

```ini
files = ../build_all_examples.py > $APPDATA\streamlink
        ../../flit.ini > $INSTDIR
```

And sure enough, the relevant line of `installer.nsi` looks like:

```nsi
SetOutPath "$APPDATA\streamlink"
```

Do you have the latest version of Pynsist? 1.8 was released a couple of months ago. And what platform are you building on?

**Comment by sbstp** [comment]
I'm using `pynsist==1.8`, my version of nsis is `2.51-1`. I'm on Debian sid, uname `Linux mu 4.7.0-1-amd64 #1 SMP Debian 4.7.6-1 (2016-10-07) x86_64 GNU/Linux`.

**Comment by takluyver** [comment]
I'm also on Linux (this machine is Fedora). The NSIS version shouldn't matter, as something's going wrong in generating the nsi input file, which happens before it invokes NSIS.

Can you push the config file you're creating to a public branch, so I can try building from the exact same file you're using?

**Comment by sbstp** [comment]
Url: https://github.com/sbstp/streamlink/tree/rcfile
I'm using a bash script to generate the pynsist config file, it's in `script/makeinstaller.sh`.

**Comment by sbstp** [comment]
You'll need to install the package (because it grabs the version number from the installed package), so if you have virtualenv you can create a new one and install the package in it.

**Comment by takluyver** [comment]
A script to generate a config file to generate a script to generate an installer. Nice ;-). If you wanted to skip one level of intermediate file, there's a public-ish API in the form of `nsist.InstallerBuilder`. Nothing wrong with doing it as you are, though :-).

Testing it now.

**Comment by takluyver** [comment]
Ah,  I think it's the shell script itself that's the issue. Bash is trying to evaluate `$APPDATA` as an environment variable, and there is none, so it substitutes the empty string. It does the same for `$INSTDIR`, but because that's the default destination, it worked anyway.

You can use `\$` to make a literal dollar sign in the script.

**Comment by sbstp** [comment]
Wow, thank you. I feel really stupid right now. Sorry about that.

**Comment by takluyver** [comment]
That's OK. It's always interesting to see the range of situations where people are using pynsist.

**Comment by sbstp** [comment]
I tested the changes on Windows and there's still nothing showing up in `$APPDATA`. I want to put a file in `%APPDATA%\streamlink`, do I have to do anything special?

**Comment by takluyver** [comment]
I think it's going into the 'all users' APPDATA folder. From [the NSIS docs](http://nsis.sourceforge.net/Docs/Chapter4.html#varconstant):

> The context of this constant (All Users or Current user) depends on the SetShellVarContext setting.

Currently, Pynsist only does 'all users' installation (issue #65), so I don't think there's any way for it to install files to a per-user directory. The workaround would be to install them in the application directory, and then copy them to `%APPDATA%` if necessary inside the application.

**Comment by sbstp** [comment]
Thanks, that's the issue.
