### ISSUE TITLE
missing 1 required positional argument 'args'

### ISSUE THREAD

**Issue by dgui** [takluyver/pynsist#86]
Hi Thomas,

I'm not sure if this is right place for this as I suspect this may be an issue with my skill level with python. Feel free to redirect me to another forum.

I have created an installer with pynsist. The main launcher and shortcuts work fine. The command I added works on the machine I used for development, but when I install elsewhere I get:

Traceback (most recent call last):
  File "c:\...\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\...\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\...\Scripts\CogsBuildDexApp.exe\__main__.py", line 9,
in <module>
TypeError: main() missing 1 required positional argument: 'args'

Here is my command def'n:

[Command BuildDexApp]
entry_point=BuildTools.BuildDexApp:main

Any suggestions?

**Comment by takluyver** [comment]
Hi Darren,

The wrapper scripts that Pynsist creates call your `main()` function with no arguments. You're expecting it to be called with (presumably) the command line args as a list. You can make the function worth both ways like this:

```python
import sys

def main(args=None):
    if args is None:
        args = sys.argv
    ...
```

**Comment by takluyver** [comment]
Closing this because it can't easily be changed in Pynsist; passing the args now would break code for everyone already using it.
