### ISSUE TITLE
Installed application shows "Unavailable" author/publisher in "Apps & features" settings

### ISSUE THREAD

**Issue by brechtm** [takluyver/pynsist#91]
I haven't been able to find out how to set an author/publisher name for the installer. Perhaps this is possible by using a custom NSI template, but reading the documentation on `nsi_template` I'd rather avoid doing that.

This could be related to #80.

**Comment by takluyver** [comment]
Hi! Is 'Apps & features' the new equivalent of the 'Add/remove programs' screen? Ironically, I don't usually use Windows myself.

The bit that adds those registry keys is here: https://github.com/takluyver/pynsist/blob/1.9/nsist/pyapp.nsi#L97

**Comment by brechtm** [comment]
Yes, it's the "Add/Remove programs" screen.

Thanks for the pointer. I didn't find my application in `Software\Microsoft\Windows\CurrentVersion\Uninstall\`, but I did find it in `SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\`. Adding a string "Publisher" works...

**Comment by takluyver** [comment]
The `WOW6432Node` makes sense for 32-bit applications, but it looks like we should be using the [SetRegView](http://nsis.sourceforge.net/Docs/Chapter4.html#setregview) command to use the main part of the registry when installing a 64-bit application.

We should probably add an option to provide an author name and add it to the registry as 'Publisher'.

**Comment by takluyver** [comment]
(PRs welcome, by the way ;-)

**Comment by brechtm** [comment]
So `WOW6432Node` doesn't make sense since I'm bundling a 64-bit Python version?

```ini
[Python]
version=3.5.2
bitness=64
format=bundled
```

I should be able to provide a PR.

**Comment by takluyver** [comment]
Yeah. I don't think it really makes a difference for this, and I don't know why 32-bit applications need a separate part of the registry anyway. But it would be neater for 64-bit applications to write data to the 64-bit version of the registry.
