### ISSUE TITLE
command --help shows wrong program name

### ISSUE THREAD

**Issue by brechtm** [takluyver/pynsist#92]
I'm using pynsist to install a command line application named "rinoh". The application uses the argparse module from the stdlib for parsing command line arguments. I configured a `--version` option as follows:

```
parser.add_argument('--version', action='version',
                    version='%(prog)s {} ({})'.format(__version__, __release_date__))
```

When installing my application using pip, `%(prog)s` resolves to `rinoh` on Mac and `rinoh.exe` on Windows.

When installed using the installer created by pynsist, `%(prog)s` resolves to `rinoh-script.py`. Would it be possible for pynists to make it output `rinoh` or `rinoh.exe`?

**Comment by takluyver** [comment]
I don't think pynsist itself can set that, but you can hardcode it where you create parser:

```python
parser = argparse.ArgumentParser(prog='rinoh')
```

https://docs.python.org/3/library/argparse.html#argumentparser-objects

**Comment by brechtm** [comment]
Ok. That's probably the better option, since `rinoh.exe` isn't exactly what I want either.
