### ISSUE TITLE
Publisher not a valid keyword

### ISSUE THREAD

**Issue by Trilarion** [takluyver/pynsist#97]
I use pynsist version 1.9 from pypi and wanted to use the publisher keyword as indicated in the docs.
It failed with:

> Error parsing configuration file:
> 'publisher' is not a valid key name for 'Application'. Must be one of these: name, version, entry_point, script, target, parameters, icon, console, extra_preamble

Could this be a bug or is the pypi version behind the documentation?

**Comment by takluyver** [comment]
Sorry, the 'publisher' key was just added in master; it's not yet in a released version. I should put a versionadded note in the docs.

**Comment by Trilarion** [comment]
Okay, thanks for the info. That answers the question. Keep up the good work.

**Comment by takluyver** [comment]
Thanks :-). I'll leave this open until I update the docs.
